### ISSUE TITLE
PDF genreres på grunnlag av melding, ikke preprossesert melding

### ISSUE THREAD

**Issue by fraadsbrandth** [navikt/pleiepengesoknad-prosessering#12]
- Dette fører til ID på barnet ikke kommer på PDF'en. Bør endre til at PDF genereres på bakgrunn av preprosessert melding.

- Fjern `formaterId` / `formatertFodselsnummer` for id på søker og barn. Skaper bare problemer når saksbehandler kopierer ut og limer inn i Gosys

**Comment by ramrock93** [comment]
#13

**Comment by ramrock93** [comment]
Adresseres i PR #13 .
